class SanskritMappings:
    """Configuration class for Sanskrit term mappings"""
    
    MAPPINGS = {
        'karma': ['action', 'deed', 'work', 'duty', 'consequence', 'cause and effect'],
        'dharma': ['righteousness', 'duty', 'law', 'moral', 'justice', 'virtue', 'natural law', 'ethical duty'],
        'yoga': ['union', 'discipline', 'practice', 'meditation', 'connection', 'spiritual path', 'self-realization'],
        'moksha': ['liberation', 'freedom', 'release', 'salvation', 'enlightenment', 'emancipation'],
        'atman': ['soul', 'self', 'spirit', 'essence', 'true self', 'inner being'],
        'brahman': ['absolute', 'supreme reality', 'universal consciousness', 'divine', 'ultimate truth'],
        'maya': ['illusion', 'delusion', 'cosmic illusion', 'temporary reality', 'material world'],
        'samsara': ['cycle of birth and death', 'worldly life', 'cycle of existence', 'material existence'],
        'guna': ['quality', 'attribute', 'property', 'nature', 'characteristic'],
        'sattva': ['goodness', 'purity', 'light', 'harmony', 'balance'],
        'rajas': ['passion', 'activity', 'energy', 'motion', 'dynamism'],
        'tamas': ['darkness', 'inertia', 'ignorance', 'dullness', 'lethargy'],
        'bhakti': ['devotion', 'love', 'dedication', 'worship', 'divine love'],
        'jnana': ['knowledge', 'wisdom', 'understanding', 'insight', 'spiritual knowledge'],
        'vedanta': ['end of knowledge', 'ultimate wisdom', 'philosophical truth', 'spiritual philosophy'],
        'upanishad': ['secret teaching', 'spiritual knowledge', 'esoteric doctrine', 'mystical teaching'],
        'guru': ['teacher', 'master', 'spiritual guide', 'mentor', 'preceptor'],
        'shishya': ['student', 'disciple', 'follower', 'learner', 'aspirant'],
        'sadhana': ['practice', 'spiritual practice', 'discipline', 'method', 'spiritual path'],
        'samadhi': ['absorption', 'deep meditation', 'enlightenment', 'union with divine', 'perfect concentration'],
        'prakriti': ['nature', 'material energy', 'primal matter', 'creation', 'physical world'],
        'purusha': ['consciousness', 'soul', 'spirit', 'observer', 'eternal witness'],
        'buddhi': ['intellect', 'intelligence', 'wisdom', 'understanding', 'discriminative faculty'],
        'manas': ['mind', 'thinking faculty', 'emotional mind', 'sensory processor'],
        'ahamkara': ['ego', 'false identity', 'I-maker', 'self-sense'],
        'chitta': ['consciousness', 'mind stuff', 'mental substance', 'subconscious mind'],
        'prana': ['life force', 'vital energy', 'breath', 'life air', 'vital force'],
        'kundalini': ['serpent power', 'spiritual energy', 'dormant power', 'evolutionary force'],
        'chakra': ['energy center', 'spiritual center', 'consciousness center', 'psychic center'],
        'asana': ['posture', 'seat', 'meditation pose', 'yoga position'],
        'pranayama': ['breath control', 'life force control', 'energy control', 'vital force regulation']
    }
